# Generated by Django 5.0.6 on 2024-05-27 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Man'), ('Female', 'Woman')], default='Male', max_length=6)),
                ('WBC', models.FloatField()),
                ('RBC', models.FloatField()),
                ('HGB', models.FloatField()),
                ('HCT', models.FloatField()),
                ('MCV', models.FloatField()),
                ('MCH', models.FloatField()),
                ('MCHC', models.FloatField()),
                ('RDW', models.FloatField()),
                ('PLT', models.FloatField()),
                ('MPV', models.FloatField()),
                ('Neutrophils', models.FloatField()),
                ('Lymphocytes', models.FloatField()),
                ('Monocytes', models.FloatField()),
                ('Eosinophils', models.FloatField()),
                ('Basophils', models.FloatField()),
                ('Glucose', models.FloatField()),
                ('Urea', models.FloatField()),
                ('Creatinine', models.FloatField()),
                ('Cholesterol', models.FloatField()),
                ('HDL', models.FloatField()),
                ('LDL', models.FloatField()),
                ('Triglycerides', models.FloatField()),
                ('ALT', models.FloatField()),
                ('AST', models.FloatField()),
                ('Bilirubin', models.FloatField()),
                ('Total_Protein', models.FloatField()),
                ('Albumin', models.FloatField()),
                ('Globulin', models.FloatField()),
                ('Calcium', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Magnesium', models.FloatField()),
                ('Sodium', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('Chloride', models.FloatField()),
                ('Continent', models.CharField(max_length=100)),
                ('Capital', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data', to='medical.customuser')),
            ],
        ),
    ]
